<?php
/**
 * @package   	OneAll Social Login
 * @copyright 	Copyright 2014 http://www.oneall.com - All rights reserved.
 * @license   	GNU/GPL 2 or later
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,USA.
 *
 * The "GNU General Public License" (GPL) is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 */

// Include Library
// http://docs.oneall.com/api/javascript/library/setup/
$oneall_sociallogin_subdomain = Mage::getStoreConfig ('oneall_sociallogin/general/subdomain');
if (! empty ($oneall_sociallogin_subdomain))
{
	?>
		<!-- OneAll.com / Social Login for Magento -->
		<script type="text/javascript">
			var oa = document.createElement('script');
			oa.type = 'text/javascript'; oa.async = true;
			oa.src = '//<?php echo $oneall_sociallogin_subdomain; ?>.api.oneall.com/socialize/library.js'
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(oa, s);
		</script>
<?php
}
?>


<?php
if (isset ($_GET ['oneall']))
{
	$pageaction = Mage::app ()->getFrontController ()->getAction ()->getFullActionName ();

	if ($_GET ['oneall'] == 'login')
	{
		// is user is come from checkout...
		if ($pageaction == 'checkout_onepage_index')
		{

			$link = Mage::getUrl ('checkout/onepage');
			echo '<meta http-equiv="refresh" content="0; url=' . $link . ' "  />';
			exit ();
		}

		$link = Mage::getUrl ('customer/account');
		echo '<meta http-equiv="refresh" content="0; url=' . $link . ' "  />';
		exit ();
	}
}
?>
